In [ ]:
#Frank Yue Ying
#yying2

In [ ]:
# Problem 2

In [2]:
# faro(n):
# Parameter: int n is the size of the matrix to create
# returns M, an ndarray, an nXn permuation matrix
def faro(n):
    I = np.identity(n).astype('int64')
    M = np.identity(n).astype('int64')
    for j in range(0,n,2):
        M[j] = I[j//2]
    for j in range(1,n+1,2):
        M[j] = I[j//2 + n//2]
    return M

In [6]:
import numpy as np
M = faro(6)
original = list(range(0,6))
newdeck = M.dot(original)
counter = 1
while np.array_equal(newdeck, original) == False:
    print(newdeck)
    counter+=1
    newdeck = M.dot(newdeck)
print("For %2d cards, it took %2d shuffles"%(6,counter))

[0 3 1 4 2 5]
[0 4 3 2 1 5]
[0 2 4 1 3 5]
For  6 cards, it took  4 shuffles


In [42]:
def main():
    import sys
    print("Part A")
    for i in range(4,53,2):
        M = faro(i)
        original = list(range(0,i))
        newdeck = M.dot(original)
        counter = 1
        while np.array_equal(newdeck, original) == False:
            counter+=1
            newdeck = M.dot(newdeck)
        print("For %2d cards, it took %2d shuffles"%(i,counter))
    print("Part B: 10x10 altered Faro matrix test")
    M = faro(10)
    original = list(range(0,10))
    ri_1 = int(input("Interchange this row: "))
    ri_2 = int(input("with that row: "))
    M[[ri_1,ri_2]] = M[[ri_2,ri_1]]
    newdeck = M.dot(original)
    print(M)
    counter = 1
    while counter < 50:
        newdeck = M.dot(newdeck)
        counter+=1
        if np.array_equal(newdeck, original) == True:
            break
    if counter == 50:
        print("Quit at 50 shuffles:")
    else:
        print("For %2d cards, it took %2d shuffles"%(10,counter))
    print(newdeck)

In [45]:
if __name__ == '__main__':
    import sys
    import numpy as np
    main()

Part A
For  4 cards, it took  2 shuffles
For  6 cards, it took  4 shuffles
For  8 cards, it took  3 shuffles
For 10 cards, it took  6 shuffles
For 12 cards, it took 10 shuffles
For 14 cards, it took 12 shuffles
For 16 cards, it took  4 shuffles
For 18 cards, it took  8 shuffles
For 20 cards, it took 18 shuffles
For 22 cards, it took  6 shuffles
For 24 cards, it took 11 shuffles
For 26 cards, it took 20 shuffles
For 28 cards, it took 18 shuffles
For 30 cards, it took 28 shuffles
For 32 cards, it took  5 shuffles
For 34 cards, it took 10 shuffles
For 36 cards, it took 12 shuffles
For 38 cards, it took 36 shuffles
For 40 cards, it took 12 shuffles
For 42 cards, it took 20 shuffles
For 44 cards, it took 14 shuffles
For 46 cards, it took 12 shuffles
For 48 cards, it took 23 shuffles
For 50 cards, it took 21 shuffles
For 52 cards, it took  8 shuffles
Part B: 10x10 altered Faro matrix test
Interchange this row: 0
with that row: 1
[[0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0