In [1]:
import numpy as np

In [74]:
def getChildren(tree):
    """
    Return a list of children. The list should be either an empty
    list, [], or a list of three tree data stuctures. If the list
    is not empty the three children in the list should be in order.
    See child index information in buildTree for details.
    
    Input:
    tree: an instance of a tree using your chosen data structure

    Return:
    List. Either an empty list or [child0_tree, child1_tree, child2_tree].
    """
    ### BEGIN YOUR CODE ###
    if len(tree) < 4:
        return []
    else:
        root_id = min(tree.keys())
        result_list = []
        for child_root in [root_id*10,root_id*10+1,root_id*10+2]:
            sub_tree = {}
            sub_tree[child_root] = tree[child_root]
            root_check = child_root*10
            while root_check < max(tree.keys()):
                sub_tree[root_check] = tree[root_check]
                sub_tree[root_check+1] = tree[root_check+1]
                sub_tree[root_check+2] = tree[root_check+2]
                root_check = root_check*10
                print("rootcheck: ",root_check)
            print("Cr: ",child_root,",subtree: ",sub_tree)
            result_list.append(sub_tree)
        return result_list
    ### END YOUR CODE ###

In [36]:
def getData(tree):
    """
    Return the Numpy data associated with just the root node in tree    

    Input:
    tree: an instance of a tree using your chosen data structure

    Return:
    NumPy array with shape (N, M) where N is the number of points
        in the data and M is the dimension of a point. N may be 
        zero, so the returned data may be an empty NumPy array 
        with shape (0, M).
    """
    ### BEGIN YOUR CODE ###
    root_id = min(tree.keys())
    return tree[root_id]

    ### END YOUR CODE ###

In [37]:
def getID(tree):
    """
    Return the integer ID of the root node of the tree.    

    Input:
    tree: an instance of a tree using your chosen data structure

    Return:
    integer
    """
    ### BEGIN YOUR CODE ###
    return min(tree.keys())

    ### END YOUR CODE ###

In [62]:
def buildTree(data, split_list, root_id):
    """
    Build a tree using any tree data structure that you choose.

    The root node of this (sub) tree should store all of data.

    If the data is empty or the split_list is empty,
    len(data) == 0 or len(split_list) == 0,
    the this root node will have no children and it should still 
    store the id and the data (even though it is empty).

    If the data is not empty and the split_list is not empty,
    the root node of this (sub) tree should have three children.
    The children should all be tree stuctures (just like the root).
    The three children should each be given a subset of data.

    Let s = split_list[0], the first integer in split_list.
    Child index 0:
        Should contain a NumPy array with shape (N_0, M)
        that containing all points in data where data[i,s] < -1.
        N_0 is the number of points that fit this criteria.
        If N_0 is zero, this child should store an empty NumPy array
        with shape (0, M), e.g. np.zeros((0,M)).
        This child should have id = root_id*10
    Child index 1:
        The same as child index 0 except:
        Child data is -1 <= data[i,s] <= 1
        Child id = root_id*10 + 1        
    Child index 2:
        The same as child index 2 except:
        Child data is data[i,s] > 1
        Child id = root_id*10 + 2        

    The tree should continue growing where the children split their 
    data based on split_list[1] and the grandchildren split their data
    based on split_list[2] and so on.

    Input:
    data: NumPy ndarray shape (N, M) representing the M-dimensional 
        coordinates of N data points. The data may be an empty NumPy
        array, i.e. len(data) == 0.
    split_index_order: List of integers. Each integer in the list is
        in the range [0,M). The list will have at most M entries.
        The list may be empty, [], in which case, this tree will not
        have any children.
    root_id: Positive integer representing the ID for the root of this
        (sub) tree. The ID for the root any child subtrees should be
        root_id*10 + index_of_that_child. So if the root_id is 7 and 
        there are three children, the IDs of the children should be
        70, 71, 72.

    Return:
    A data structure of your choosing that represents the resulting
        tree.
    """
    ### BEGIN YOUR CODE ###
    tree = {}
    def buildTree_rec(tree,data,split_list,root_id):
        s = split_list[0]
        for n in range(3):
            childID = root_id*10+n
            child_data = np.zeros((0,data.shape[1]))
            if n == 0:
                child_data = data[data[:,s] < -1]
            elif n == 1:
                child_data = data[(data[:,s] > -1) & (data[:,s] < 1)]
            elif n == 2:
                child_data = data[data[:,s] > 1]
            tree[childID] = child_data
            if len(split_list) > 1:
                tree = buildTree_rec(tree,child_data,split_list[1:],childID)
        return tree
    if len(data) == 0 or len(split_list) == 0:
        tree[root_id] = data
        return tree
    elif len(data) > 0 and len(split_list) > 0:
        tree[root_id] = data
        tree = buildTree_rec(tree,data, split_list,root_id)
    print(*tree.keys()," ")
    return tree
    ### END YOUR CODE ###

# Helps the autograder keep track of what nodes have been printed
# via printNode. You shouldn't ever modify this. It only gets
# updated inside printNode()
PRINT_NODE_LIST = []

In [39]:
def printNode(tree):
    """
    Print information about the just the root node of tree.
    Prints:
    id
    data

    Input:
    tree: an instance of a tree using your chosen data structure

    Return:
    None
    """
    print(getID(tree))
    print(getData(tree))

    # Helps the autograder keep track of what nodes have been printed
    # via printNode. You shouldn't ever modify this. It only gets
    # updated inside printNode()
    PRINT_NODE_LIST.append(getID(tree))

In [66]:
def printTreeBF(tree):
    """
    Print each node in the whole tree using a breadth-first 
    traversal. To make the autograder happy, print the parent
    before the children and make sure any children are printed 
    in increasing order of their index, i.e., index0, then 
    index1, then index2.

    Autograder details: Use printNode for each node (id then data)
    Don't print another information, and don't print any blank lines.

    Input:
    tree: an instance of a tree using your chosen data structure

    Return:
    None
    """
    ### BEGIN YOUR CODE ###
    root_id = min(tree.keys())
    printNode(tree)
    search_id = root_id*10
    children = getChildren(tree)
    children_list = children
    while search_id < max(tree.keys()):
        children_list1 = []
        for i in children_list:
            child_tree = i
            printNode(child_tree)
            children = getChildren(child_tree)
            children_list1.extend(children)
        search_id = search_id*10
        children_list = children_list1.copy()
    ### END YOUR CODE ###

In [54]:
def printTreeDF(tree):
    """
    Print each node in the whole tree using a depth-first 
    traversal. To make the autograder happy, print the parent
    before the children and make sure any children are printed 
    in increasing order of their index, i.e., index0, then 
    index1, then index2.

    Autograder details: Use printNode for each node (id then data)
    Don't print another information, and don't print any blank lines.

    Input:
    tree: an instance of a tree using your chosen data structure

    Return:
    None
    """
    ### BEGIN YOUR CODE ###
    root_id = min(tree.keys())
    def df_rec(tree, root_id):
        if root_id*10 in tree.keys():
            children = getChildren(tree)
            printNode(tree)
            for i,v in enumerate(children):
                child_tree = v
                if i == 0:
                    printNode(child_tree)
                df_rec(child_tree, root_id*10+i)
        else:
            printNode(tree)
    df_rec(tree,root_id)

    ### END YOUR CODE ###

In [50]:
data1 = np.array([
[-1.5, -0.5, -0.2],
[0.3, 1.3, 0.0],
[-1.3, -1.4, -2.1],
[0.9, 1.5, -0.6]])

task1_test0()
task1_testA(data1)
task1_testB(data1)
task1_testC(data1)

tree0 root
5
[]

tree1A root
6
[[-1.5 -0.5 -0.2]
 [ 0.3  1.3  0. ]
 [-1.3 -1.4 -2.1]
 [ 0.9  1.5 -0.6]]

tree1B root
1
[[-1.5 -0.5 -0.2]
 [ 0.3  1.3  0. ]
 [-1.3 -1.4 -2.1]
 [ 0.9  1.5 -0.6]]
tree1B children
10
[[-1.5 -0.5 -0.2]
 [-1.3 -1.4 -2.1]]
11
[[ 0.3  1.3  0. ]
 [ 0.9  1.5 -0.6]]
12
[]

tree1C root
1
[[-1.5 -0.5 -0.2]
 [ 0.3  1.3  0. ]
 [-1.3 -1.4 -2.1]
 [ 0.9  1.5 -0.6]]
tree1C first child
10
[[-1.5 -0.5 -0.2]
 [-1.3 -1.4 -2.1]]
tree1C first grandchild
100
[[-1.3 -1.4 -2.1]]



In [75]:
data1 = np.array([
[-1.5, -0.5, -0.2],
[0.3, 1.3, 0.0],
[-1.3, -1.4, -2.1],
[0.9, 1.5, -0.6]])
PRINT_NODE_LIST = [] # Reset list before printing tree
task2_testBF(data1)

# PRINT_NODE_LIST = [] # Reset list before printing tree
# task2_testDF(data1)

# PRINT_NODE_LIST = [] # Reset list before printing tree
# test_randData()

1 10 100 1000 1001 1002 101 1010 1011 1012 102 1020 1021 1022 11 110 1100 1101 1102 111 1110 1111 1112 112 1120 1121 1122 12 120 1200 1201 1202 121 1210 1211 1212 122 1220 1221 1222  
tree BF
1
[[-1.5 -0.5 -0.2]
 [ 0.3  1.3  0. ]
 [-1.3 -1.4 -2.1]
 [ 0.9  1.5 -0.6]]
rootcheck:  1000
rootcheck:  10000
Cr:  10 ,subtree:  {10: array([[-1.3, -1.4, -2.1]]), 100: array([[-1.3, -1.4, -2.1]]), 101: array([], shape=(0, 3), dtype=float64), 102: array([], shape=(0, 3), dtype=float64), 1000: array([[-1.3, -1.4, -2.1]]), 1001: array([], shape=(0, 3), dtype=float64), 1002: array([], shape=(0, 3), dtype=float64)}
rootcheck:  1100
rootcheck:  11000
Cr:  11 ,subtree:  {11: array([[-1.5, -0.5, -0.2],
       [ 0.3,  1.3,  0. ],
       [ 0.9,  1.5, -0.6]]), 110: array([[-1.5, -0.5, -0.2]]), 111: array([[ 0.3,  1.3,  0. ],
       [ 0.9,  1.5, -0.6]]), 112: array([], shape=(0, 3), dtype=float64), 1100: array([], shape=(0, 3), dtype=float64), 1101: array([[-1.5, -0.5, -0.2]]), 1102: array([], shape=(0, 3), d

In [52]:
def task1_test0():
    data0 = np.zeros((0,3))

    tree0 = buildTree(data0, [0, 1, 2], 5)
    print("tree0 root")
    printNode(tree0)
    print() # Print blank line

def task1_testA(data):
    tree1A = buildTree(data, [], 6)
    print("tree1A root")
    printNode(tree1A)
    print() # Print blank line

def task1_testB(data):
    tree1B = buildTree(data, [0], 1)
    print("tree1B root")
    printNode(tree1B)
    print("tree1B children")
    for child in getChildren(tree1B):
        printNode(child)
    print() # Print blank line

def task1_testC(data):
    tree1C = buildTree(data, [0, 1, 2], 1)
    print("tree1C root")
    printNode(tree1C)

    tree1C_firstChild = getChildren(tree1C)[0]
    print("tree1C first child")
    printNode(tree1C_firstChild)

    tree1C_firstGrandchild = getChildren(tree1C_firstChild)[0]
    print("tree1C first grandchild")
    printNode(tree1C_firstGrandchild)

    print() # Print blank line
def task2_testBF(data):
    tree1D = buildTree(data, [2, 0, 1], 1)

    print("tree BF")
    printTreeBF(tree1D)
    print("Order of printed nodes:", PRINT_NODE_LIST)
    print() # Print blank line

def task2_testDF(data):
    tree1D = buildTree(data, [2, 0, 1], 1)

    print("tree1D DF")
    printTreeDF(tree1D)
    print("Order of printed nodes:", PRINT_NODE_LIST)
    print() # Print blank line

def test_randData():
    N = 40
    M = 5
    depth = 4

    data = np.random.uniform(-2, 2, (N,M))
    split_list = np.random.choice(M, size=depth, replace=False).tolist()

    tree = buildTree(data, split_list, 1)

    print("random data tree BF")
    printTreeBF(tree)
    print("Order of printed nodes:", PRINT_NODE_LIST)
    print() # Print blank line