In [ ]:
#Frank Yue Ying
#2021-11-09

In [1]:
#Problem 1
sentence = "Create a str variable named sentence and set it to the words in this sentence"
words = sentence.split(" ")
with open("words.txt",'w') as f:
    for w in words:
        f.write(w+"\n")

In [6]:
#Problem 2
mywords = []
with open("words.txt",'r') as f:
    for w in f:
        mywords.append(w.strip())
print(mywords)
print(words==mywords)

['Create', 'a', 'str', 'variable', 'named', 'sentence', 'and', 'set', 'it', 'to', 'the', 'words', 'in', 'this', 'sentence']
True


In [7]:
#Problem 3
mylist = [ ('dog', 'cat', 'mouse'), ('tetra', 'goldfish', 'trout'), ('hyrax','wombat', 'gopher')]
with open("mylist.csv",'w') as f:
    for tu in mylist:
        f.write(",".join(tu)+"\n")

In [10]:
#Problem 4
newlist = list()
with open("mylist.csv",'r') as f:
    for line in f:
        newlist.append(tuple(line.strip().split(",")))
print(newlist)
print(mylist==newlist)

[('dog', 'cat', 'mouse'), ('tetra', 'goldfish', 'trout'), ('hyrax', 'wombat', 'gopher')]
True


In [13]:
#Problem 5
import pickle
data = {15:'book', 27:'pen', 12:'tablet', 48:'ink', 44:'pencil', 30:'eraser',72:'wombat'}
print(data)
print(data.keys())
print(data.values())
with open("mydata.bin",'wb') as f:
    pickle.dump(data,f)

{15: 'book', 27: 'pen', 12: 'tablet', 48: 'ink', 44: 'pencil', 30: 'eraser', 72: 'wombat'}
dict_keys([15, 27, 12, 48, 44, 30, 72])
dict_values(['book', 'pen', 'tablet', 'ink', 'pencil', 'eraser', 'wombat'])


In [17]:
#Problem 6
with open("mydata.bin",'rb') as f:
    newdata = pickle.load(f)
print(newdata)
print(data==newdata)
print(newdata.keys())
print(newdata.values())

{15: 'book', 27: 'pen', 12: 'tablet', 48: 'ink', 44: 'pencil', 30: 'eraser', 72: 'wombat'}
True
dict_keys([15, 27, 12, 48, 44, 30, 72])
dict_values(['book', 'pen', 'tablet', 'ink', 'pencil', 'eraser', 'wombat'])


In [52]:
#Problem 7
import numpy as np
A = np.array([4, 0, -1, 9]) # A
B = np.array([10, 3, -2, -2]) # B
C = np.array([ [2, 4], [1, 1] ]) # C
D = np.array([ [1, -1], [-1, 0] ]) # D
names = ["A","B","C","D"]
for i,v in enumerate([A,B,C,D]):
    print("Array "+names[i]+":")
    print("   Array value:",v)
    print("   Array shape:",v.shape)
    print("   Array dimension:",v.ndim)
    
print("C's first row:")
print(C[0,:])
##print(C[0][:])

print("D's first Column:")
print(D[:,0])

Array A:
   Array value: [ 4  0 -1  9]
   Array shape: (4,)
   Array dimension: 1
Array B:
   Array value: [10  3 -2 -2]
   Array shape: (4,)
   Array dimension: 1
Array C:
   Array value: [[2 4]
 [1 1]]
   Array shape: (2, 2)
   Array dimension: 2
Array D:
   Array value: [[ 1 -1]
 [-1  0]]
   Array shape: (2, 2)
   Array dimension: 2
C's first row:
[2 4]
D's first Column:
[ 1 -1]


In [48]:
#Problem 8
print("a. Sum and different of A and B")
print(A+B)
print(A-B)
print("b. Sum and different of C and D")
print(C+D)
print(C-D)
print("c. Sum of A and C")
try:
    print(A+C)
except:
    print("Cannot do sum of A and C because the shape is different.")
print("d. multiplication of A and B")
print(A*B)
print(B*A)
print("e. multiplication of C and D")
print(C*D)
print(D*C)
print("f. multiplication of C and B")
try:
    print(C*B)
except:
    print("Cannot do multiplication of C and B because the shape is different")

a. Sum and different of A and B
[14  3 -3  7]
[-6 -3  1 11]
b. Sum and different of C and D
[[3 3]
 [0 1]]
[[1 5]
 [2 1]]
c. Sum of A and C
Cannot do sum of A and C because the shape is different.
d. multiplication of A and B
[ 40   0   2 -18]
[ 40   0   2 -18]
e. multiplication of C and D
[[ 2 -4]
 [-1  0]]
[[ 2 -4]
 [-1  0]]
f. multiplication of C and B
Cannot do multiplication of C and B because the shape is different
